# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OWNhMTgxODllZjY0NGVmMDA1YjE5NzQwMmNmNjQ1ZWJlODBmZGMzMzhjNWM3ZDVjNWNmYTAxM2RlYjJlMzRjNmU0YWE3ZmY2ODc2MjA5NzQ4MWM0NmEwNWM0MzYxODAzZjQ2YjJlYWI5MjM2MTY3OWMwNTUyM2Q0ZjA4MTAxZTE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
